# Generated by Django 5.1.4 on 2025-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prediccion', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('hora_subida', models.TimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPredicciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prediccion', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('hora_subida', models.TimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
