# Generated by Django 5.1.4 on 2025-01-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0002_delete_historialpredicciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_subida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_subida',
            field=models.TimeField(),
        ),
    ]
