# Generated by Django 5.1.4 on 2025-01-09 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0004_alter_historial_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_subida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_subida',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
