# Generated by Django 5.1.4 on 2025-01-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0006_alter_historial_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='prediccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
